GET http://localhost:3000/people


###
GET http://localhost:3000/index

###

POST http://localhost:3000/people
Content-Type: application/json

{
    "name": "Tyran smith",
    "gender": "male"
}

###
GET http://localhost:3000/

###


GET http://localhost:3000/posts


###


GET http://localhost:3000/posts/people